version: "3.9"
services:
  mediconnect-db:
    image: postgres:latest
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  mediconnect-api:
    build: .
    ports:
      - "3000:3000"
    environment:
      DB_SCHEMA: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: postgres
    depends_on:
      - mediconnect-db
