INSERT INTO "subscription" ("id", "name", "price", "ratePerMonth", "overageFeePerRequest") VALUES ('price_1OAvrbCuQ03psKfdyIIdy7RL', 'Basic', 0, 500, 0.01);
INSERT INTO "subscription" ("id", "name", "price", "ratePerMonth", "overageFeePerRequest") VALUES ('price_1O826qCuQ03psKfdg4E6Yr8s', 'Pro', 10.90, 1000, 0.01);
INSERT INTO "subscription" ("id", "name", "price", "ratePerMonth", "overageFeePerRequest") VALUES ('price_1O826qCuQ03psKfd90pC4r80', 'Enterprise', 49.90, 10000, 0.005);

INSERT INTO "user" ("id", "name", "email", "password", "subscriptionId") VALUES ('1', 'John Doe', 'john.doe@mediconnect.com', '123456', 1);
INSERT INTO "user" ("id", "name", "email", "password", "subscriptionId") VALUES ('2', 'Tom Miller', 'tom.miller@mediconnect.com', '123456', 2);
INSERT INTO "user" ("id", "name", "email", "password", "subscriptionId") VALUES ('3', 'David Smith', 'david.smith@mediconnect.com', '123456', 3);

INSERT INTO "api_key" ("id", "ownerId", "key", "name", "createdAt", "expiresAt") VALUES (1, 1, 'Q4fjlJ5sG6rzlrKDxM2d9VAFLiyMKpWU', 'Default', '2023-10-22 00:00:00', '2031-12-31 23:59:59');
INSERT INTO "api_key" ("id", "ownerId", "key", "name", "createdAt", "expiresAt") VALUES (2, 2, 'KgIQRjq1z99frjSVzLvQtyNQT4JlRvu9', 'Default', '2023-10-24 00:00:00', '2031-12-31 23:59:59');
INSERT INTO "api_key" ("id", "ownerId", "key", "name", "createdAt", "expiresAt") VALUES (3, 3, 'qJ5Ta22dFsFhqZl9RrmTUVBfDXU6zx1j', 'APP 1', '2023-10-25 00:00:00', '2031-12-31 23:59:59');
INSERT INTO "api_key" ("id", "ownerId", "key", "name", "createdAt", "expiresAt") VALUES (4, 3, '7FGBDeNVMgM8bY404ok3EUM6fMFlpUD9', 'APP 2', '2023-10-25 00:01:00', '2031-12-31 23:59:59');

/* update autogenerated id sequences */
SELECT setval('api_key_id_seq', (SELECT MAX(id) FROM "api_key"));