import { type MigrationInterface, type QueryRunner } from 'typeorm'

export class CreateUserSubscription21699623799786 implements MigrationInterface {
  name = 'CreateUserSubscription21699623799786'

  public async up (queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query('ALTER TABLE "subscription" DROP COLUMN "stripeSubscriptionId"')
    await queryRunner.query('ALTER TABLE "user_subscription" DROP CONSTRAINT "FK_a7575d9d46b42a9d7f275be1ec4"')
    await queryRunner.query('ALTER TABLE "subscription" DROP CONSTRAINT "PK_8c3e00ebd02103caa1174cd5d9d"')
    await queryRunner.query('ALTER TABLE "subscription" DROP COLUMN "id"')
    await queryRunner.query('ALTER TABLE "subscription" ADD "id" character varying NOT NULL')
    await queryRunner.query('ALTER TABLE "subscription" ADD CONSTRAINT "PK_8c3e00ebd02103caa1174cd5d9d" PRIMARY KEY ("id")')
    await queryRunner.query('ALTER TABLE "user_subscription" DROP CONSTRAINT "FK_403d98d1638533c09f9b185929b"')
    await queryRunner.query('ALTER TABLE "user" DROP CONSTRAINT "FK_2760508c1091408ac1c11ec1fd9"')
    await queryRunner.query('ALTER TABLE "user_subscription" DROP CONSTRAINT "PK_e843ed2446cfda0ad317b09de8f"')
    await queryRunner.query('ALTER TABLE "user_subscription" ADD CONSTRAINT "PK_a7575d9d46b42a9d7f275be1ec4" PRIMARY KEY ("subscriptionId")')
    await queryRunner.query('ALTER TABLE "user_subscription" DROP COLUMN "userId"')
    await queryRunner.query('ALTER TABLE "user_subscription" ADD "userId" character varying NOT NULL')
    await queryRunner.query('ALTER TABLE "user_subscription" DROP CONSTRAINT "PK_a7575d9d46b42a9d7f275be1ec4"')
    await queryRunner.query('ALTER TABLE "user_subscription" ADD CONSTRAINT "PK_e843ed2446cfda0ad317b09de8f" PRIMARY KEY ("subscriptionId", "userId")')
    await queryRunner.query('ALTER TABLE "user_subscription" DROP CONSTRAINT "PK_e843ed2446cfda0ad317b09de8f"')
    await queryRunner.query('ALTER TABLE "user_subscription" ADD CONSTRAINT "PK_403d98d1638533c09f9b185929b" PRIMARY KEY ("userId")')
    await queryRunner.query('ALTER TABLE "user_subscription" DROP COLUMN "subscriptionId"')
    await queryRunner.query('ALTER TABLE "user_subscription" ADD "subscriptionId" character varying NOT NULL')
    await queryRunner.query('ALTER TABLE "user_subscription" DROP CONSTRAINT "PK_403d98d1638533c09f9b185929b"')
    await queryRunner.query('ALTER TABLE "user_subscription" ADD CONSTRAINT "PK_e843ed2446cfda0ad317b09de8f" PRIMARY KEY ("userId", "subscriptionId")')
    await queryRunner.query('ALTER TABLE "api_key" DROP CONSTRAINT "FK_74d2236b1de818d00bd3fd01602"')
    await queryRunner.query('ALTER TABLE "user" DROP CONSTRAINT "PK_cace4a159ff9f2512dd42373760"')
    await queryRunner.query('ALTER TABLE "user" DROP COLUMN "id"')
    await queryRunner.query('ALTER TABLE "user" ADD "id" character varying NOT NULL')
    await queryRunner.query('ALTER TABLE "user" ADD CONSTRAINT "PK_cace4a159ff9f2512dd42373760" PRIMARY KEY ("id")')
    await queryRunner.query('ALTER TABLE "user" DROP COLUMN "subscriptionUserId"')
    await queryRunner.query('ALTER TABLE "user" ADD "subscriptionUserId" character varying')
    await queryRunner.query('ALTER TABLE "user" DROP COLUMN "subscriptionSubscriptionId"')
    await queryRunner.query('ALTER TABLE "user" ADD "subscriptionSubscriptionId" character varying')
    await queryRunner.query('ALTER TABLE "api_key" DROP COLUMN "ownerId"')
    await queryRunner.query('ALTER TABLE "api_key" ADD "ownerId" character varying')
    await queryRunner.query('ALTER TABLE "user_subscription" ADD CONSTRAINT "FK_403d98d1638533c09f9b185929b" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION')
    await queryRunner.query('ALTER TABLE "user_subscription" ADD CONSTRAINT "FK_a7575d9d46b42a9d7f275be1ec4" FOREIGN KEY ("subscriptionId") REFERENCES "subscription"("id") ON DELETE NO ACTION ON UPDATE NO ACTION')
    await queryRunner.query('ALTER TABLE "user" ADD CONSTRAINT "FK_2760508c1091408ac1c11ec1fd9" FOREIGN KEY ("subscriptionUserId", "subscriptionSubscriptionId") REFERENCES "user_subscription"("userId","subscriptionId") ON DELETE NO ACTION ON UPDATE NO ACTION')
    await queryRunner.query('ALTER TABLE "api_key" ADD CONSTRAINT "FK_74d2236b1de818d00bd3fd01602" FOREIGN KEY ("ownerId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION')
  }

  public async down (queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query('ALTER TABLE "api_key" DROP CONSTRAINT "FK_74d2236b1de818d00bd3fd01602"')
    await queryRunner.query('ALTER TABLE "user" DROP CONSTRAINT "FK_2760508c1091408ac1c11ec1fd9"')
    await queryRunner.query('ALTER TABLE "user_subscription" DROP CONSTRAINT "FK_a7575d9d46b42a9d7f275be1ec4"')
    await queryRunner.query('ALTER TABLE "user_subscription" DROP CONSTRAINT "FK_403d98d1638533c09f9b185929b"')
    await queryRunner.query('ALTER TABLE "api_key" DROP COLUMN "ownerId"')
    await queryRunner.query('ALTER TABLE "api_key" ADD "ownerId" integer')
    await queryRunner.query('ALTER TABLE "user" DROP COLUMN "subscriptionSubscriptionId"')
    await queryRunner.query('ALTER TABLE "user" ADD "subscriptionSubscriptionId" integer')
    await queryRunner.query('ALTER TABLE "user" DROP COLUMN "subscriptionUserId"')
    await queryRunner.query('ALTER TABLE "user" ADD "subscriptionUserId" integer')
    await queryRunner.query('ALTER TABLE "user" DROP CONSTRAINT "PK_cace4a159ff9f2512dd42373760"')
    await queryRunner.query('ALTER TABLE "user" DROP COLUMN "id"')
    await queryRunner.query('ALTER TABLE "user" ADD "id" SERIAL NOT NULL')
    await queryRunner.query('ALTER TABLE "user" ADD CONSTRAINT "PK_cace4a159ff9f2512dd42373760" PRIMARY KEY ("id")')
    await queryRunner.query('ALTER TABLE "api_key" ADD CONSTRAINT "FK_74d2236b1de818d00bd3fd01602" FOREIGN KEY ("ownerId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION')
    await queryRunner.query('ALTER TABLE "user_subscription" DROP CONSTRAINT "PK_e843ed2446cfda0ad317b09de8f"')
    await queryRunner.query('ALTER TABLE "user_subscription" ADD CONSTRAINT "PK_403d98d1638533c09f9b185929b" PRIMARY KEY ("userId")')
    await queryRunner.query('ALTER TABLE "user_subscription" DROP COLUMN "subscriptionId"')
    await queryRunner.query('ALTER TABLE "user_subscription" ADD "subscriptionId" integer NOT NULL')
    await queryRunner.query('ALTER TABLE "user_subscription" DROP CONSTRAINT "PK_403d98d1638533c09f9b185929b"')
    await queryRunner.query('ALTER TABLE "user_subscription" ADD CONSTRAINT "PK_e843ed2446cfda0ad317b09de8f" PRIMARY KEY ("subscriptionId", "userId")')
    await queryRunner.query('ALTER TABLE "user_subscription" DROP CONSTRAINT "PK_e843ed2446cfda0ad317b09de8f"')
    await queryRunner.query('ALTER TABLE "user_subscription" ADD CONSTRAINT "PK_a7575d9d46b42a9d7f275be1ec4" PRIMARY KEY ("subscriptionId")')
    await queryRunner.query('ALTER TABLE "user_subscription" DROP COLUMN "userId"')
    await queryRunner.query('ALTER TABLE "user_subscription" ADD "userId" integer NOT NULL')
    await queryRunner.query('ALTER TABLE "user_subscription" DROP CONSTRAINT "PK_a7575d9d46b42a9d7f275be1ec4"')
    await queryRunner.query('ALTER TABLE "user_subscription" ADD CONSTRAINT "PK_e843ed2446cfda0ad317b09de8f" PRIMARY KEY ("userId", "subscriptionId")')
    await queryRunner.query('ALTER TABLE "user" ADD CONSTRAINT "FK_2760508c1091408ac1c11ec1fd9" FOREIGN KEY ("subscriptionUserId", "subscriptionSubscriptionId") REFERENCES "user_subscription"("userId","subscriptionId") ON DELETE NO ACTION ON UPDATE NO ACTION')
    await queryRunner.query('ALTER TABLE "user_subscription" ADD CONSTRAINT "FK_403d98d1638533c09f9b185929b" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION')
    await queryRunner.query('ALTER TABLE "subscription" DROP CONSTRAINT "PK_8c3e00ebd02103caa1174cd5d9d"')
    await queryRunner.query('ALTER TABLE "subscription" DROP COLUMN "id"')
    await queryRunner.query('ALTER TABLE "subscription" ADD "id" SERIAL NOT NULL')
    await queryRunner.query('ALTER TABLE "subscription" ADD CONSTRAINT "PK_8c3e00ebd02103caa1174cd5d9d" PRIMARY KEY ("id")')
    await queryRunner.query('ALTER TABLE "user_subscription" ADD CONSTRAINT "FK_a7575d9d46b42a9d7f275be1ec4" FOREIGN KEY ("subscriptionId") REFERENCES "subscription"("id") ON DELETE NO ACTION ON UPDATE NO ACTION')
    await queryRunner.query('ALTER TABLE "subscription" ADD "stripeSubscriptionId" character varying NOT NULL')
  }
}
